/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_errorcase_4 (
    input [0:0] yesno,
    input [15:0] in,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] z;
  
  always @* begin
    z = in;
    if (yesno == 1'h1) begin
      z = z + 16'h0001;
    end
    out = z;
  end
endmodule
