/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alufn_inputter_2 (
    input [1:0] in,
    output reg [5:0] out
  );
  
  
  
  localparam ADD = 6'h00;
  
  localparam SUB = 6'h01;
  
  localparam CMPEQ = 6'h33;
  
  reg [5:0] z;
  
  always @* begin
    z = 6'h00;
    if (in == 2'h0) begin
      z = 6'h00;
    end
    if (in == 2'h1) begin
      z = 6'h01;
    end
    if (in == 2'h2) begin
      z = 6'h33;
    end
    out = z;
  end
endmodule
